<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
    <DebuggerSupport>true</DebuggerSupport>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
    <EnableMicrosoftExtensionsConfigurationBinderSourceGenerator>true</EnableMicrosoftExtensionsConfigurationBinderSourceGenerator>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <EnforceExtendedAnalyzerRules>false</EnforceExtendedAnalyzerRules>
    <FFTestProject>true</FFTestProject>
    <Features>strict;flow-analysis</Features>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <GenerateNeutralResourcesLanguageAttribute>true</GenerateNeutralResourcesLanguageAttribute>
    <IlcGenerateStackTraceData>false</IlcGenerateStackTraceData>
    <IlcOptimizationPreference>Size</IlcOptimizationPreference>
    <ImplicitUsings>disable</ImplicitUsings>
    <IsPackable>False</IsPackable>
    <IsPublishable>False</IsPublishable>
    <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
    <IsTrimmable>true</IsTrimmable>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
    <LangVersion>latest</LangVersion>
    <NeutralLanguage>en</NeutralLanguage>
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditLevel>low</NuGetAuditLevel>
    <NuGetAuditMode>all</NuGetAuditMode>
    <Nullable>enable</Nullable>
    <OptimizationPreference>speed</OptimizationPreference>
    <OutputType>Library</OutputType>
    <RunAOTCompilation>false</RunAOTCompilation>
    <TargetFramework>net10.0</TargetFramework>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <TieredCompilation>true</TieredCompilation>
    <TieredPGO>true</TieredPGO>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
    <WarnOnPackingNonPackableProject>false</WarnOnPackingNonPackableProject>
    <WarningsAsErrors />
  </PropertyGroup>
  <Import Project="$(SolutionDir)FunFair.props" Condition="Exists('$(SolutionDir)FunFair.props')" />
  <ItemGroup>
    <ProjectReference Include="../FunFair.Test.Infrastructure/FunFair.Test.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" IncludeAssets="compile;runtime" />
    <PackageReference Include="FluentValidation" Version="12.1.1" IncludeAssets="compile;runtime" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AsyncFixer" Version="2.1.0" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="codecracker.CSharp" Version="1.1.0" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="Credfeto.Enumeration.Source.Generation" Version="1.2.152.2216" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="CSharpIsNullAnalyzer" Version="0.2.19" PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="FunFair.CodeAnalysis" Version="7.2.13.2323" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="Meziantou.Analyzer" Version="3.0.200" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="Philips.CodeAnalysis.DuplicateCodeAnalyzer" Version="2.0.0" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="Philips.CodeAnalysis.MaintainabilityAnalyzers" Version="2.0.0" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="Roslynator.Analyzers" Version="5.0.0" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="SecurityCodeScan.VS2019" Version="5.6.7" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="SerilogAnalyzer" Version="0.15.0" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="SmartAnalyzers.CSharpExtensions.Annotations" Version="4.2.11" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.33.0.1635" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="SourceLink.Create.CommandLine" Version="2.8.3" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="ToStringWithoutOverrideAnalyzer" Version="0.6.0" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="xunit.analyzers" Version="2.0.0" PrivateAssets="All" ExcludeAssets="runtime" />
  </ItemGroup>
</Project>
