<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
    <CodeAnalysisRuleSet>$(SolutionDir)\CodeAnalysis.ruleset</CodeAnalysisRuleSet>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
    <DebuggerSupport>true</DebuggerSupport>
    <Description>FunFair Common Test Infrastructure for building xUnit tests on top of.</Description>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
    <EnableMicrosoftExtensionsConfigurationBinderSourceGenerator>true</EnableMicrosoftExtensionsConfigurationBinderSourceGenerator>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnablePackageValidation>true</EnablePackageValidation>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <EnforceExtendedAnalyzerRules>false</EnforceExtendedAnalyzerRules>
    <FFTestProject>true</FFTestProject>
    <Features>strict;flow-analysis</Features>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <GenerateNeutralResourcesLanguageAttribute>true</GenerateNeutralResourcesLanguageAttribute>
    <GenerateSBOM>true</GenerateSBOM>
    <IlcGenerateStackTraceData>false</IlcGenerateStackTraceData>
    <IlcOptimizationPreference>Size</IlcOptimizationPreference>
    <ImplicitUsings>disable</ImplicitUsings>
    <IncludeSymbols>true</IncludeSymbols>
    <IsPackable>True</IsPackable>
    <IsPublishable>False</IsPublishable>
    <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
    <IsTrimmable>false</IsTrimmable>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
    <LangVersion>latest</LangVersion>
    <NeutralLanguage>en</NeutralLanguage>
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditLevel>high</NuGetAuditLevel>
    <NuGetAuditMode>all</NuGetAuditMode>
    <Nullable>enable</Nullable>
    <OptimizationPreference>speed</OptimizationPreference>
    <OutputType>Library</OutputType>
    <PackageTags>FunFair, Test Helpers, Test</PackageTags>
    <RepositoryUrl>https://github.com/funfair-tech/funfair-server-test</RepositoryUrl>
    <RunAOTCompilation>false</RunAOTCompilation>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <TieredCompilation>true</TieredCompilation>
    <TieredPGO>true</TieredPGO>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
    <WarningsAsErrors />
  </PropertyGroup>
  <Import Project="$(SolutionDir)FunFair.props" Condition="Exists('$(SolutionDir)FunFair.props')" />
  <ItemGroup>
    <PackageReference Include="AutoBogus.NSubstitute" Version="2.13.1" />
    <PackageReference Include="BenchmarkDotNet" Version="0.15.4" />
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="Castle.Core" Version="5.2.1" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="Meziantou.Extensions.Logging.Xunit.v3" Version="1.1.16" />
    <PackageReference Include="NonBlocking" Version="2.1.2" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="xunit.v3.assert" Version="3.1.0" />
    <PackageReference Include="xunit.v3.extensibility.core" Version="3.1.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AsyncFixer" Version="1.6.0" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="codecracker.CSharp" Version="1.1.0" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="Credfeto.Enumeration.Source.Generation" Version="1.2.129.1430" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="CSharpIsNullAnalyzer" Version="0.1.593" PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="FunFair.CodeAnalysis" Version="7.1.25.1550" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="Meziantou.Analyzer" Version="2.0.239" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Sbom.Targets" Version="4.1.2" PrivateAssets="All" ExcludeAssets="runtime" Condition="$(EnableSbom)=='True'" />
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="NSubstitute.Analyzers.CSharp" Version="1.0.17" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="Philips.CodeAnalysis.DuplicateCodeAnalyzer" Version="1.6.4" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="Philips.CodeAnalysis.MaintainabilityAnalyzers" Version="1.9.1" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="Roslynator.Analyzers" Version="4.14.1" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="SecurityCodeScan.VS2019" Version="5.6.7" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="SerilogAnalyzer" Version="0.15.0" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="SmartAnalyzers.CSharpExtensions.Annotations" Version="4.2.11" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.15.0.120848" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="SourceLink.Create.CommandLine" Version="2.8.3" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="ToStringWithoutOverrideAnalyzer" Version="0.6.0" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="xunit.analyzers" Version="1.24.0" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" PrivateAssets="All" />
  </ItemGroup>
</Project>