<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
        <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(MSBuildProjectName).xml</DocumentationFile>
        <EnablePackageValidation>true</EnablePackageValidation>
        <Features>strict;flow-analysis</Features>
        <GenerateNeutralResourcesLanguageAttribute>true</GenerateNeutralResourcesLanguageAttribute>
        <ImplicitUsings>disable</ImplicitUsings>
        <IncludeOpenAPIAnalyzers>true</IncludeOpenAPIAnalyzers>
        <IsPackable>True</IsPackable>
        <IsPublishable>False</IsPublishable>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <OutputType>Library</OutputType>
        <TargetFramework>net5.0</TargetFramework>
        <TieredCompilation>true</TieredCompilation>
        <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
        <WarningsAsErrors />
    </PropertyGroup>
    <PropertyGroup>
        <AnalysisLevel>latest</AnalysisLevel>
        <AnalysisMode>AllEnabledByDefault</AnalysisMode>
        <CodeAnalysisRuleSet>$(SolutionDir)\CodeAnalysis.ruleset</CodeAnalysisRuleSet>
        <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    </PropertyGroup>
    <PropertyGroup>
        <Description>FunFair Common Test Infrastructure for building xUnit tests on top of.</Description>
        <NeutralLanguage>en</NeutralLanguage>
        <PackageTags>FunFair, Test Helpers, Test</PackageTags>
        <RepositoryUrl>https://github.com/funfair-tech/funfair-server-test</RepositoryUrl>
    </PropertyGroup>
    <Import Project="$(SolutionDir)FunFair.props" />
    <ItemGroup>
        <!-- Note in this project ONLY we need to exclude the test SDK from being packed -->
    </ItemGroup>
    <ItemGroup>
        <Content Remove="content\testhost.dll" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Castle.Core" Version="4.4.1" />
        <PackageReference Include="Dapper" Version="2.0.123" />
        <PackageReference Include="FluentValidation.AspNetCore" Version="10.3.5" />
        <PackageReference Include="NonBlocking" Version="1.1.2" />
        <PackageReference Include="NSubstitute" Version="4.2.2" />
        <PackageReference Include="xunit" Version="2.4.1" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="AsyncFixer" Version="1.5.1" PrivateAssets="All" />
        <PackageReference Include="FunFair.CodeAnalysis" Version="5.7.0.995" PrivateAssets="All" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.0.0" PrivateAssets="All" />
        <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.0.64" PrivateAssets="All" />
        <PackageReference Include="NSubstitute.Analyzers.CSharp" Version="1.0.15" PrivateAssets="All" />
        <PackageReference Include="Roslynator.Analyzers" Version="3.3.0" PrivateAssets="All" />
        <PackageReference Include="SonarAnalyzer.CSharp" Version="8.32.0.39516" PrivateAssets="All" />
        <PackageReference Include="SourceLink.Create.CommandLine" Version="2.8.3" PrivateAssets="All" />
        <PackageReference Include="ToStringWithoutOverrideAnalyzer" Version="0.6.0" PrivateAssets="All" />
        <PackageReference Include="xunit.analyzers" Version="0.10.0" PrivateAssets="All" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3" PrivateAssets="All" />
    </ItemGroup>
</Project>